FROM golang:1.22.1-alpine

WORKDIR /app

RUN apk add --no-cache curl


COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin


ENV PATH=$PATH:/go/bin

EXPOSE 8080

CMD ["air"]
