# Use the official Golang image as the base image
FROM golang:1.22.1-alpine

# Set the working directory inside the container
WORKDIR /app

# Install goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Copy the migrations directory
COPY migrations /app/migrations

# Set the entrypoint to run goose
ENTRYPOINT ["goose", "-dir", "/app/migrations"]
