apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: choregate-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: choregate-role
subjects:
- kind: ServiceAccount
  name: choregate
  namespace: choregate
